name: movie_manager_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  provider: ^6.1.2
  flutter_rating_bar: ^4.0.1
  mask_text_input_formatter: ^2.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  # Se você quiser usar a fonte 'Inter', descomente as linhas abaixo e adicione os arquivos de fonte
  # na pasta 'assets/fonts/' do seu projeto. Caso contrário, mantenha-as comentadas.
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700
